apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-express-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: express-{{ .Values.buildNumber }}
  type: {{ .Values.express_svc.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.express_svc.ports.port }}
      targetPort: 3001
