apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongo-{{ .Values.buildNumber }}
  type: {{ .Values.mongo_svc.type }}
  ports:
    - port: {{ .Values.mongo_svc.ports.port }}
      targetPort: 27017
