apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-react-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: react-{{ .Values.buildNumber }}
  type: {{ .Values.react_svc.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.react_svc.ports.port }}
      targetPort: 3000
